/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp6;

/**
 *
 * @author Hernán Funes
 */
public class MenuGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MenuGeneral
     */
    public MenuGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuAdministracion = new javax.swing.JMenu();
        jMIProductos = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMIRubro = new javax.swing.JMenuItem();
        jMINombre = new javax.swing.JMenuItem();
        jMIPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        JMenuAdministracion.setText("Administracion");
        JMenuAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuAdministracionActionPerformed(evt);
            }
        });

        jMIProductos.setText("Productos");
        jMIProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProductosActionPerformed(evt);
            }
        });
        JMenuAdministracion.add(jMIProductos);

        jMenuBar1.add(JMenuAdministracion);

        jMenuConsultas.setText("Consultas");

        jMIRubro.setText("Por Rubro");
        jMIRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRubroActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMIRubro);

        jMINombre.setText("Por Nombre");
        jMenuConsultas.add(jMINombre);

        jMIPrecio.setText("Por Precio");
        jMIPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPrecioActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMIPrecio);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRubroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIRubroActionPerformed

    private void jMIPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIPrecioActionPerformed

    private void jMIProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeProductos gdp = new GestionDeProductos();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jMIProductosActionPerformed

    private void JMenuAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuAdministracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuAdministracion;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMINombre;
    private javax.swing.JMenuItem jMIPrecio;
    private javax.swing.JMenuItem jMIProductos;
    private javax.swing.JMenuItem jMIRubro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    // End of variables declaration//GEN-END:variables
}
